services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: csit_fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'

  app:
    image: application
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./start.sh:/app/start.sh
    env_file:
      - env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/csit_fastapi
    ports:
      - '127.0.0.1:8020:8000'
    build:
      context: .
    pull_policy: build
    entrypoint: sh -c "./start.sh"

volumes:
  postgres_data:
